# Generated by Django 3.2.10 on 2022-06-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('Idnumber', models.CharField(max_length=50)),
                ('DateOfBirth', models.DateField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='DatasetTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=50)),
                ('Idnumber', models.CharField(max_length=50)),
                ('DateOfBirth', models.DateField(max_length=8)),
            ],
        ),
    ]
